/* DICAS PARA SABER SE É MELHOR UTILIZAR FUNÇÕES OU PROCEDIMENTOS: */

// A FUNÇÃO SEMPRE E OBRIGATORIAMENTE VAI RETORNAR UM VALOR.
// FUNÇÃO UTILIZA INT, FLOAT, CHAR, DOUBLE... NA HORA DE CRIAR O SUBPROGRAMA
// EM FUNÇÃO NÃO SE UTILIZA COMANDOS DE ENTRADA E SAÍDA, APENAS UMA TAREFA É RECEBIDA, EXECUTADA E RETORNADO RESULTADO;
/* SE PRECISAR REPRODUZIR UM RESULTADO, OU NÃO UTILIZAR OS COMANDOS DE ENTRADA E SAÍDA, APENAS SE FOR RECEBER, 
EXECUTAR E RETORNAR VALOR, SE UTILIZA FUNÇÃO. */

// O PROCEDIMENTO NÃO RETORNA NENHUM VALOR, SÓ EXECUTA A TAREFA.
// PROCEDIMENTO UTILIZA VOID NA HORA DE CRIAR O SUBPROGRAMA;
// EM PROCEDIMENTOS PODEM SER UTILIZADOS COMANDOS DE ENTRADA E SAÍDA.
/* SE O PROGRAMA NÃO FOR PRODUZIR RESULTADO, OU TER QUE RETORNAR VÁRIOS VALORES, OU SE PRECISAR UTILIZAR 
COMANDOS DE ENTRADA E SAÍDA, É MELHOR PROCEDIMENTOS */

#include <stdio.h>

const int tam = 10;

void intervalo(int m, int n){
    int k;
    for(k = m; k <= n; k++){
        printf(" %d ", k);
    }
    printf("\n");
}
void main(){
    int m, n;
    printf("Insira os limites do intervalo: ");
    scanf("%d%d", &m, &n);

    intervalo(m, n);
}
    

